# Generated by Django 4.2.1 on 2023-08-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('finish_date', models.DateField()),
                ('finish_time', models.TimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
