# Generated by Django 4.2.1 on 2023-08-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='user_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
