# Generated by Django 4.2.1 on 2023-08-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTask', '0002_taskmodel_like_taskmodel_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
