# Generated by Django 4.2.1 on 2023-08-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myTask', '0003_taskmodel_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='task_id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
