# Generated by Django 4.2.1 on 2023-10-25 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myTask', '0005_likemodel_likemodel_like_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('content', models.CharField(blank=True, max_length=250)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myTask.taskmodel')),
            ],
        ),
    ]
