# Generated by Django 4.2.1 on 2023-09-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
